version: '3.8'

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bot-network

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-botdb}
      POSTGRES_USER: ${POSTGRES_USER:-botuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-botpassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge 